[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

# Bat
[templates.bat]
input_path = '~/.config/matugen/templates/matugen-bat-colors.tmTheme'
output_path = '~/.config/bat/themes/matugen-bat-colors.tmTheme'
post_hook = 'bat cache --build' 

[templates.kitty]
input_path = './templates/matugen-kitty.conf'
output_path = '~/.config/kitty/kitty.conf'

[templates.spicetify]
input_path = '~/.config/matugen/templates/spotify-colors.ini'
output_path = '~/.config/spicetify/Themes/Comfy/color.ini'

[templates.foot]
input_path = './templates/matugen-foot.ini'
output_path = '~/.config/foot/foot.ini'

[templates.zellij]
input_path = './templates/matugen-zellij.kdl'
output_path = '~/.config/zellij/config.kdl'

[templates.starship]
input_path = './templates/matugen-starship.toml'
output_path = '~/.config/starship.toml'

[templates.hypr]
input_path = './templates/matugen-hypr-colors.conf'
output_path = '~/.config/hypr/hyprland/colors.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/matugen-waybar'
output_path = '~/.config/waybar/config'
# post_hook = 'pkill -sigusr2 waybar'

[templates.waybar-css]
input_path = '~/.config/matugen/templates/matugen-waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -sigusr2 waybar'

[templates.rofi]
input_path = '~/.config/matugen/templates/matugen-rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.nvim]
input_path = '~/.config/matugen/templates/matugen-nvim-colors.lua'
output_path = '~/.local/state/nvim/colors.lua'

[templates.swaync]
input_path = '~/.config/matugen/templates/matugen-swaync-style.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'pkill -sigusr2 swaync'

[templates.tmux]
input_path = './templates/matugen-tmux.conf'
output_path = '~/.config/tmux/tmux.conf'

# Gtk3
[templates.gtk3]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

# GTk4
[templates.gtk4]
input_path = '~/.config/matugen/templates/matugen-gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

# Qt5
[templates.qt5]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen-qt5ct.conf'

# Qt6
[templates.qt6]
input_path = '~/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen-qt6ct.conf'

# Kvantum
[templates.kvantum]
input_path = '~/.config/matugen/templates/matugen.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

