#!/bin/bash


### CONFIGURATION ###
riverctl background-color 0xff131318
riverctl border-color-focused 0xff424078
riverctl border-color-unfocused 0xff464559
riverctl border-width 0
riverctl declare-mode passthrough
riverctl default-layout rivertile
riverctl focus-follows-cursor normal
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad natural-scroll enabled
riverctl input pointer-2-7-SynPS/2_Synaptics_TouchPad tap enabled
riverctl keyboard-layout us
riverctl map locked None XF86AudioLowerVolume spawn 'pamixer -d 5'
riverctl map locked None XF86AudioMedia spawn 'playerctl play-pause'
riverctl map locked None XF86AudioMute spawn 'pamixer --toggle-mute'
riverctl map locked None XF86AudioNext spawn 'playerctl next'
riverctl map locked None XF86AudioPlay spawn 'playerctl play-pause'
riverctl map locked None XF86AudioPrev spawn 'playerctl previous'
riverctl map locked None XF86AudioRaiseVolume spawn 'pamixer -i 5'
riverctl map locked None XF86Eject spawn 'eject -T'
riverctl map locked None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
riverctl map locked None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
riverctl map normal Alt B spawn firefox
riverctl map normal Alt C spawn 'chromium --app=https://chatgpt.com'
riverctl map normal Alt H resize horizontal -100
riverctl map normal Alt J resize vertical 100
riverctl map normal Alt K resize vertical -100
riverctl map normal Alt L resize horizontal 100
riverctl map normal Alt P spawn 'swaync-client --toggle-panel'
riverctl map normal Alt+Shift H snap left
riverctl map normal Alt+Shift J snap down
riverctl map normal Alt+Shift K snap up
riverctl map normal Alt+Shift L snap right
riverctl map normal Control+Shift S spawn wlogout
riverctl map normal None XF86AudioLowerVolume spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-'
riverctl map normal None XF86AudioMedia spawn 'playerctl play-pause'
riverctl map normal None XF86AudioMicMute spawn 'wpctl set-mute @DEFAULT_SOURCE@ toggle'
riverctl map normal None XF86AudioMute spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
riverctl map normal None XF86AudioNext spawn 'playerctl next'
riverctl map normal None XF86AudioPlay spawn 'playerctl play-pause'
riverctl map normal None XF86AudioPrev spawn 'playerctl previous'
riverctl map normal None XF86AudioRaiseVolume spawn 'wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+'
riverctl map normal None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
riverctl map normal None XF86MonBrightnessUp spawn 'brightnessctl set +5%'
riverctl map normal None XF86Search spawn blueberry
riverctl map normal Super A spawn 'rofi -show drun -theme ~/.config/rofi/theme.rasi'
riverctl map normal Super B spawn chromium
riverctl map normal Super Comma focus-output previous
riverctl map normal Super Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super E spawn thunar
riverctl map normal Super F toggle-fullscreen
riverctl map normal Super F11 enter-mode passthrough
riverctl map normal Super H focus-view left
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super L focus-view right
riverctl map normal Super Left send-layout-cmd rivertile "main-location left"
riverctl map normal Super Period focus-output next
riverctl map normal Super Q close
riverctl map normal Super Return zoom
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Space toggle-float
riverctl map normal Super Tab spawn foot
riverctl map normal Super Up send-layout-cmd rivertile "main-location top"
riverctl map normal Super V spawn '/nix/store/zvps85kqam3bh9w18wwa7k2mkw9kh139-rofi-clipboard.sh/bin/rofi-clipboard.sh'
riverctl map normal Super+Control T spawn '/nix/store/0y90ljlsrikq1jns8qqm3p5vhiimrrzb-waypaper-2.5/bin/waypaper'
riverctl map normal Super+Shift Comma send-to-output previous
riverctl map normal Super+Shift E exit
riverctl map normal Super+Shift H move left 100
riverctl map normal Super+Shift J move down 100
riverctl map normal Super+Shift K move up 100
riverctl map normal Super+Shift L move right 100
riverctl map normal Super+Shift Period send-to-output next
riverctl map passthrough Super F11 enter-mode normal
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl rule-add -app-id 'bar' csd
riverctl rule-add -app-id 'float*' -title 'foo' float
riverctl set-repeat 50 300
riverctl spawn 'waybar &'
riverctl spawn 'swaync &'
riverctl spawn 'nm-applet &'
riverctl spawn 'swww-daemon --format xrgb'
riverctl spawn 'wl-paste --type text --watch cliphist store &'
riverctl spawn 'wl-paste --type image --watch cliphist store &'
riverctl spawn 'discord &'
riverctl spawn powermode-indicator

### EXTRA CONFIGURATION ###
# wlr-randr --output eDP-1 --mode 1920x1080 --pos 0,1080
# wlr-randr --output HDMI-A-2 --mode 1920x1080 --pos 0,0
rivertile -view-padding 6 -outer-padding 6 &

for i in $(seq 1 9); do
  tags=$((1 << ($i - 1)))

  # switch to tag--workspace?? (i)
  riverctl map normal Super $i set-focused-tags $tags

  # tag view with num -- move focused window to (i)
  riverctl map normal Super+Alt $i set-view-tags $tags

  # Super+Control+[1-9] to toggle focus of tag [0-8]
  riverctl map normal Super+Control $i toggle-focused-tags $tags

  # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
  riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done


### SYSTEMD INTEGRATION ###
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP NIXOS_OZONE_WL XCURSOR_THEME XCURSOR_SIZE && systemctl --user stop river-session.target && systemctl --user start river-session.target


