local lazy = require("lazy")

lazy.setup({
	require("plugs.mini.starter"),
	require("plugs.snacks"),
	require("plugs.ui.lualine"),
	--require("plugs.ui.telescope"),
	require("plugs.ui.noice"),
	require("plugs.ui.neotree"),
	require("plugs.ui.tokyonight"),
	-- require("plugs.ui.catppuccin"),
	require("plugs.fmt.treesitter"),
	require("plugs.fmt.todo"),
	require("plugs.fmt.conform"),
	require("plugs.lsp.mason"),
	require("plugs.lsp.nvim-cmp"),
	require("plugs.ai.avante"),
	require("plugs.ai.copilot"),
	require("plugs.mini.comment"),
	require("plugs.mini.surround"),
	require("plugs.mini.pairs"),
	require("plugs.etc.wakatime"),
	require("plugs.etc.presence"),
	require("plugs.etc.tmux-nav"),
	require("plugs.etc.highlight-colors"),

	install = { colorscheme = { "tokyonight" } },

	-- ui = {
	-- 	size = { width = 0.8, height = 0.8 },
	-- 	border = "solid",
	-- 	icons = {
	-- 		cmd = " ",
	-- 		config = "",
	-- 		event = "",
	-- 		ft = " ",
	-- 		init = " ",
	-- 		import = " ",
	-- 		keys = " ",
	-- 		lazy = "鈴 ",
	-- 		loaded = "●",
	-- 		not_loaded = "○",
	-- 		plugin = " ",
	-- 		runtime = " ",
	-- 		source = " ",
	-- 		start = "",
	-- 		task = "✔ ",
	-- 		list = { "●", "➜", "★", "‒" },
	-- 	},
	-- 	throttle = 20,
	-- },
	-- defaults = { lazy = true },
	-- performance = {
	-- 	cache = {
	-- 		enabled = true,
	-- 		path = vim.fn.stdpath("cache") .. "/lazy/cache",
	-- 		ttl = 3600 * 24 * 5,
	-- 		disable_events = { "VimEnter", "BufReadPre", "UIEnter" },
	-- 	},
	-- 	reset_packpath = true,
	-- 	rtp = {
	-- 		disabled_plugins = {
	-- 			"2html_plugin",
	-- 			"getscript",
	-- 			"getscriptPlugin",
	-- 			"gzip",
	-- 			"netrw",
	-- 			"netrwPlugin",
	-- 			"netrwSettings",
	-- 			"netrwFileHandlers",
	-- 			"logipat",
	-- 			"matchit",
	-- 			"matchparen",
	-- 			"tar",
	-- 			"tarPlugin",
	-- 			"rrhelper",
	-- 			"spellfile_plugin",
	-- 			"vimball",
	-- 			"vimballPlugin",
	-- 			"zip",
	-- 			"zipPlugin",
	-- 			"logipat",
	-- 			"matchit",
	-- 			"tutor",
	-- 			"rplugin",
	-- 			"syntax",
	-- 			"synmenu",
	-- 			"optwin",
	-- 			"compiler",
	-- 			"bugreport",
	-- 			"ftplugin",
	-- 			"archlinux",
	-- 			"fzf",
	-- 			"tutor_mode_plugin",
	-- 			"sleuth",
	-- 			"vimgrep",
	-- 		},
	-- 	},
	-- },
})
